language: perl
perl:
matrix:
  include:
    - perl: "5.30"
      dist: xenial
    - perl: "5.26"
      dist: xenial
    - perl: "5.22"
      dist: xenial
    - perl: "5.20"
      dist: trusty
    - perl: "5.18"
      dist: trusty
    - perl: "5.16"
      dist: precise
    - perl: "5.14"
      dist: precise
    - perl: "5.12"
      dist: precise
    - perl: "5.10"
      dist: precise
    - perl: "5.8"
      dist: precise

branches:
 except:
  - /appveyor/
sudo: false

script:
  - perl Makefile.PL && env HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest
