language: perl
arch:
  - arm64
matrix:
  include:
    - dist: xenial
      perl: 5.24
    - dist: bionic
      perl: 5.26
    - dist: focal
      perl: 5.32
#matrix:
#  include:
#    - perl: "5.30"
#      dist: xenial
#    - perl: "5.26"
#      dist: xenial
#    - perl: "5.22"
#      dist: xenial
#    - perl: "5.20"
#      dist: trusty
#    - perl: "5.18"
#      dist: trusty
#    - perl: "5.16"
#      dist: precise
#    - perl: "5.14"
#      dist: precise
#    - perl: "5.12"
#      dist: precise
#    - perl: "5.10"
#      dist: precise
#    - perl: "5.8"
#      dist: precise
#sudo: false

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/

script:
  - perl Makefile.PL && env HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest
