name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'
  pull_request:
  workflow_dispatch:

jobs:

  test_on_host:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       include:
         - os: 'ubuntu-22.04'
         - os: 'ubuntu-24.04'
    steps:
    - name: apt hacks
      # /etc/apt/sources.list should be sufficient; all the other repositories are possibly problematic
      run: |
        sudo rm -f /etc/apt/sources.list.d/*.list
        sudo apt-get update -qq
      if: "startsWith(matrix.os, 'ubuntu-')"
    - uses: taiki-e/checkout-action@v1
    - name: "perl dependency installation (ubuntu)"
      run: |
        sudo apt-get install -q --no-install-recommends -y cpanminus
        cpanm --sudo --quiet --installdeps --notest . || ( cat ~/.cpanm/work/*/build.log; false )
      if: "startsWith(matrix.os, 'ubuntu-')"
    - name: Build and test
      run: |
        set -e
        perl Makefile.PL
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make test
      if: "!startsWith(matrix.os,'windows-')"

  test_in_container:
    name: Test with perl ${{ matrix.perlimage }} (deps=${{ matrix.deps||'false' }}, optional_deps=${{ matrix.optional_deps||'false' }})
    runs-on: ubuntu-latest
    container: perl:${{ matrix.perlimage }}
    strategy:
      matrix:
        include:
          - perlimage: 5.8.9-threaded-stretch
            deps: true
          - perlimage: 5.10.1-buster
            deps: true
          - perlimage: 5.12.5-stretch
            deps: true
          - perlimage: 5.14.4-stretch
            deps: true
          - perlimage: 5.16.3-buster
            deps: true
          - perlimage: 5.18.4-buster
            deps: true
          - perlimage: 5.22.4-stretch
            deps: true
          - perlimage: 5.36.0-slim-bullseye
            deps: true
            optional_deps: true
          - perlimage: 5.38.0-slim-bookworm
            deps: true
          - perlimage: 5.40.0-slim-bookworm
            deps: true
          - perlimage: 5.42.0-slim-bookworm
            deps: true
    steps:
    - name: apt hacks
      run: |
        set -e
        CODENAME=$(perl -nle '/^VERSION_CODENAME="?([^"]+)/ and $codename=$1; /^VERSION="\d+ \((.*)\)/ and $maybe_codename=$1; END { print $codename || $maybe_codename }' /etc/os-release)
        case "$CODENAME" in
          wheezy|jessie|stretch|buster)
            echo "APT::Get::AllowUnauthenticated 1;" > /etc/apt/apt.conf.d/02allow-unsigned
            echo "deb [check-valid-until=no] http://archive.debian.org/debian $CODENAME main"                   >  /etc/apt/sources.list
            echo "deb [check-valid-until=no] http://archive.debian.org/debian-security/ $CODENAME/updates main" >> /etc/apt/sources.list
            ;;
        esac
    - uses: taiki-e/checkout-action@v1
    - name: Install dependencies
      # Note: currently dependencies must be installed; the test suite does not skip correctly on missing Sort::Naturally
      run: |
        set -e
        cpanm --quiet --installdeps --notest . || ( cat ~/.cpanm/work/*/build.log; false )
      if: matrix.deps
    - name: Install optional dependencies
      run: |
        set -e
        cpanm --quiet --notest IPC::Run Test::Differences || ( cat ~/.cpanm/work/*/build.log; false )
      if: matrix.deps
    - name: Build and test
      run: |
        set -e
        perl Makefile.PL
        HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest
